// ============================================================
//  Auditoría Interna Especial — Servicio Walmart Chile
//  Datos: Informe Final v5 (28-07-2026) · §8 Hallazgos, §9 Patrones, §11 Plan
// ============================================================

// Los quince hallazgos, en orden de severidad descendente (orden del informe).
window.HALLAZGOS = [
  {
    code: 'HAL-002',
    tit: 'Causas terminadas reportadas como vigentes',
    cls: 'Incumplimiento contractual',
    sev: 'Crítica',
    deriva: 'OBS-002',
    criterio: 'Nivel 2 · Contrato',
    desc: 'Se reportaron al cliente 8.004 causas como vigentes al 8 de mayo de 2026, sobre una base construida a partir de lo abierto en el sistema de origen, sin validación contra el Poder Judicial y con la revisión de fondo expresamente diferida. El 46% del universo no correspondía: 3.833 causas y 4.075 imputados. El 23 de mayo el cliente identificó el defecto con precisión, y la segunda entrega se produjo veintiún días después sin que consten cambios en el procedimiento. El destinatario calificó el hecho como «falla grave de control». La causa técnica del defecto de origen permanece abierta.',
    acciones: ['B', 'C', 'G'],
  },
  {
    code: 'HAL-015',
    tit: 'No existe una capa de control sobre la ejecución de los procesos',
    cls: 'Ausencia de diseño de control',
    sev: 'Crítica',
    deriva: 'OBS-028',
    criterio: 'Nivel 4 · Buenas prácticas',
    desc: 'En diecinueve de veintiocho procesos observados no existe punto de control, y ninguno de los veintiocho reúne umbral, alerta, responsable y frecuencia. La falta está en los siete procesos y en los cinco equipos. De las veintiocho fallas acreditadas, cuatro las advirtió la propia operación; nueve el cliente y quince esta revisión. Los equipos declararon setenta y cuatro elementos de control frente a los once registrados, y seis ya operaban sin figurar en el registro. Es el hallazgo que sostiene la conclusión general del encargo.',
    acciones: ['L'],
  },
  {
    code: 'HAL-004',
    tit: 'El indicador de asistencia de testigos se publica sin declarar su universo',
    cls: 'Deficiencia de diseño',
    sev: 'Alta',
    deriva: 'OBS-011',
    criterio: 'Nivel 4 · Buenas prácticas',
    desc: 'El cálculo es correcto y reproducible: la fórmula oficial da 45,6% frente al 45,2% publicado. El defecto es de presentación y de construcción. La lámina entregada al cliente publica 999 citaciones, 343 asistencias y 45,2% de forma contigua, y 343 sobre 999 da 34,3%. En la misma lámina conviven dos universos con 257 registros de diferencia. Y el denominador excluye a los testigos que ya no trabajan, que es la causa más frecuente de inasistencia.',
    acciones: ['A'],
  },
  {
    code: 'HAL-005',
    tit: 'El gobierno del contrato y de la relación no está bajo control',
    cls: 'Ausencia de diseño de control',
    sev: 'Alta',
    deriva: 'OBS-013 · 021 · 022 y un antecedente sin observación',
    criterio: 'Nivel 4 · Buenas prácticas',
    desc: 'Tres dimensiones del mismo defecto. Vigencia: el contrato venció el 31 de enero de 2026 y la prórroga se perfeccionó el 3 de febrero, con una cláusula de plazo que admite dos lecturas sin resolver. Exigibilidad: cuatro de los diez niveles de servicio tienen la multa «a definir» y nunca se definió; y el plazo de doce horas que el cliente espera no está pactado. Interlocución: no hay contraparte única y los reportes se distribuyen sin regla de destinatario.',
    acciones: ['E', 'M'],
  },
  {
    code: 'HAL-006',
    tit: 'La continuidad del universo de eventos no se gestionó ante los cambios de plataforma',
    cls: 'Ausencia de diseño de control',
    sev: 'Alta',
    deriva: 'OBS-006 · OBS-023',
    criterio: 'Nivel 4 · Buenas prácticas',
    desc: 'En cuatro meses el cliente modificó dos veces el origen de los eventos, y en ninguno de los dos casos el prestador levantó acta de impacto, acordó la interfaz ni estableció un plan de reconciliación. La trazabilidad se sostiene en una reconstrucción manual diaria por criterios sustitutos. No se afirma pérdida de información: el área sostiene que el consolidado diario recupera lo no notificado, y esa respuesta no está refutada.',
    acciones: ['D'],
  },
  {
    code: 'HAL-007',
    tit: 'No existe un proceso de actualización y control de vigencia de las causas',
    cls: 'Ausencia de diseño de control',
    sev: 'Alta',
    deriva: 'OBS-027',
    criterio: 'Nivel 4 · Buenas prácticas',
    desc: 'La actualización del estado procesal no está diseñada como proceso. La propia Dirección de Operaciones la declara «distribuida en distintos procesos sin coordinación», sin control de vigencia, sin fuente de verdad exclusiva y sin capacidad dimensionada. El instrumento interno vigente documenta funciones de notificación, no un control de vigencia. Es la causa de proceso de HAL-002, y su remediación está diseñada y no constituida.',
    acciones: ['B'],
  },
  {
    code: 'HAL-008',
    tit: 'Los controles de acceso a datos personales que el contrato exige no están implementados',
    cls: 'Incumplimiento contractual',
    sev: 'Alta',
    deriva: 'Sin observación de origen',
    criterio: 'Nivel 2 · Contrato',
    desc: 'La cláusula 11.4 del Contrato 2022 obliga a establecer controles de acceso a los datos personales y a restringirlos a quien necesariamente los requiera. Se verificaron cinco hechos que se apartan: claves vigentes en texto plano en un manual distribuido, repositorios con datos personales abiertos por enlace, cuentas genéricas compartidas sin trazabilidad, planillas con datos de imputados y testigos circulando por correo, y diecinueve casillas de notificación de revisión manual.',
    acciones: ['F'],
  },
  {
    code: 'HAL-009',
    tit: 'La cadena de citación del testigo no tiene aseguramiento',
    cls: 'Ausencia de diseño de control',
    sev: 'Alta',
    deriva: 'OBS-008 · 010 · 024 · 026',
    criterio: 'Nivel 4 · Buenas prácticas',
    desc: 'La citación atraviesa cuatro eslabones —preparación, citación, comparecencia y registro— y ninguno verifica al anterior. El control de preparación está suspendido y su columna registra 0%. El contacto se canaliza por intermediarios sin confirmación de recepción. No existe mecanismo para validar si los abogados realizaron el contacto. Y el testigo no tiene identidad propia en el registro. Las cuatro observaciones declaran suficiencia limitada; el conjunto se corrobora.',
    acciones: ['H'],
  },
  {
    code: 'HAL-010',
    tit: 'Los entregables al cliente se producen a mano y sin control sistémico',
    cls: 'Ausencia de diseño de control',
    sev: 'Alta',
    deriva: 'OBS-003 · 004 · 009 · 012',
    criterio: 'Nivel 4 · Buenas prácticas',
    desc: 'Cuatro procesos de tres frentes distintos producen los entregables mediante trabajo manual sobre planillas paralelas al sistema, sin documentación del flujo, sin registro de las transformaciones y sin verificación de integridad antes del envío. El documento emitido lo formula así: «la fidelidad del entregable descansa en el trabajo manual de una persona, no en un control». Y las correcciones no dejan rastro.',
    acciones: ['B'],
  },
  {
    code: 'HAL-011',
    tit: 'La información sobre la conformación del equipo legal no es exacta',
    cls: 'Incumplimiento contractual',
    sev: 'Alta',
    deriva: 'OBS-016',
    criterio: 'Nivel 4 · Buenas prácticas',
    desc: 'Se informó al cliente que todos los abogados que tramitan sus causas son internos. Los registros del propio prestador identifican del orden de treinta prestadores externos, uno de ellos una sociedad de cinco abogados. Dieciséis de treinta y uno no tienen indicadores ni multas pactadas, y el 43% no tiene acceso al sistema. La evidencia es suficiente para la inconsistencia y limitada para la intención, sobre la que no se concluye.',
    acciones: ['E'],
  },
  {
    code: 'HAL-012',
    tit: 'La cartera judicializada antes del cambio de modelo quedó sin regla',
    cls: 'Ausencia de diseño de control',
    sev: 'Alta',
    deriva: 'OBS-018',
    criterio: 'Nivel 4 · Buenas prácticas',
    desc: 'Cuando el modelo de intervención cambió, ningún instrumento previó qué hacer con las causas ya judicializadas. La laguna consta por omisión en el texto del anexo de 2018, firmado por ambas partes. El 44,6% de los registros informados al cliente —3.573 de 8.003— pertenece a ese universo sin regla. Y el acuerdo de 2020 que se invoca para suplirla fue desconocido por escrito por el cliente: «no contamos con respaldo escrito de ese acuerdo».',
    acciones: ['J'],
  },
  {
    code: 'HAL-013',
    tit: 'La criminalidad interna no es trazable y hay causas prescritas',
    cls: 'Incumplimiento contractual',
    sev: 'Alta',
    deriva: 'OBS-029',
    criterio: 'Nivel 4 · Buenas prácticas',
    desc: 'El contrato exige un protocolo para esta categoría y el protocolo no consta. La categoría no es trazable en el registro, de modo que no puede revisarse como conjunto. Las tres causas vigentes están paralizadas: una se encontraría prescrita y otra tiene audiencia sobre prescripción fijada para el 28 de julio de 2026. Es el único hallazgo del encargo cuyo efecto es irreversible: una acción penal extinguida no se recupera.',
    acciones: ['I'],
  },
  {
    code: 'HAL-001',
    tit: 'Denominaciones que no corresponden a la entidad medida',
    cls: 'Deficiencia de diseño',
    sev: 'Media',
    deriva: 'OBS-001',
    criterio: 'Nivel 4 · Buenas prácticas',
    desc: 'El modelo de reportería empleaba denominaciones jurídicas para nombrar entidades distintas de las que esos términos designan, sin definición documentada ni declaración de la unidad contada. El archivo del 8 de mayo sostiene cuatro magnitudes: 8.004 comunicadas, 8.003 filas, 7.140 causas por identificador judicial y 7.227 causas identificables. Explica entre el 5,9% y el 7,6% de la reducción del universo: no explica el descuadre que originó el encargo.',
    acciones: ['A'],
  },
  {
    code: 'HAL-003',
    tit: 'El indicador de cobertura ACD recorta su propio universo',
    cls: 'Ausencia de diseño de control',
    sev: 'Media',
    deriva: 'OBS-005',
    criterio: 'Nivel 4 · Buenas prácticas',
    desc: 'Coexisten tres definiciones vigentes e incompatibles, todas construyendo el denominador por inclusión. El campo que la implementa carece de valor en el 39,2% de los casos —1.535 de 3.913— y esos registros salen del universo sin contabilizarse como cobertura fallida. El indicador tiende por construcción al 100%. Y el campo que registraba por qué no se asistió se retiró de la vista del cliente por «ruido comercial» declarado, hecho que se consigna con cautela expresa.',
    acciones: ['A'],
  },
  {
    code: 'HAL-014',
    tit: 'Los procesos de seguridad en tienda operan sin procedimiento estandarizado',
    cls: 'Ausencia de diseño de control',
    sev: 'Media',
    deriva: 'OBS-019 · OBS-020',
    criterio: 'Nivel 4 · Buenas prácticas',
    desc: 'La vinculación de bandas mediante circuito cerrado carece de los controles esperables, y el control de las descargas en tienda no tiene protocolo: se realiza en base al criterio de cada guardia, lo que obliga al prestador a practicar revisiones adicionales. Parte de la materia excede su ámbito —los guardias no son su personal—, y por eso se le imputa no haber requerido el estándar ni documentado el retrabajo que su ausencia le traslada.',
    acciones: ['K'],
  },
];

// Los cuatro patrones por causa raíz (§9).
window.PATRONES = [
  {
    id: 'P1',
    tit: 'Ausencia de gobernanza de definiciones sobre los indicadores',
    hallazgos: ['HAL-001', 'HAL-003', 'HAL-004'],
    comun: 'Tres indicadores, tres procesos y tres equipos responsables distintos. En los tres casos ninguna función define, aprueba, versiona ni valida que un indicador declare lo que mide antes de publicarse.',
    riesgo: 'Ninguna cifra que el servicio reporta es interpretable por su receptor ni comparable entre períodos. El riesgo no es que un indicador esté mal: es que no hay forma de saber si lo está.',
    accion: 'Crear la función de gobernanza de definiciones, con diccionario único de indicadores, ficha obligatoria por indicador y control de salida previo a todo envío.',
  },
  {
    id: 'P2',
    tit: 'Ausencia de dueño del proceso que produce el dato',
    hallazgos: ['HAL-002', 'HAL-006', 'HAL-007', 'HAL-010'],
    comun: 'El estado procesal, el universo de eventos, la actualización del registro y la producción de los entregables no tienen responsable asignado: la función existe repartida entre roles, sin dueño, sin fuente de verdad y sin capacidad dimensionada.',
    riesgo: 'El dato se degrada sin que nadie lo advierta. Sin dueño, el universo vuelve a degradarse y el próximo descuadre lo detectará otra vez el cliente.',
    accion: 'Designar dueño por dato crítico y por entregable, con fuente de verdad exclusiva, flujo documentado, registro de transformaciones y conciliación periódica contra la fuente externa.',
  },
  {
    id: 'P3',
    tit: 'Obligaciones y compromisos vigentes sin control de cumplimiento',
    hallazgos: ['HAL-005', 'HAL-008', 'HAL-011', 'HAL-013'],
    comun: 'Cuatro obligaciones específicas y vigentes —el marco contractual, los controles de acceso a datos personales, la exactitud de lo informado sobre el servicio y el protocolo de criminalidad interna— y ninguna función con el encargo de verificar su cumplimiento.',
    riesgo: 'El instrumento que rige el servicio no está bajo control, y su incumplimiento se descubre cuando alguien lo revisa por otra razón. En criminalidad interna ese riesgo ya se materializó de forma irreversible.',
    accion: 'Establecer un control de cumplimiento contractual con inventario de obligaciones exigibles, responsable de verificarlas y alerta sobre vencimientos y plazos de caducidad.',
  },
  {
    id: 'P4',
    tit: 'Procesos sin verificación de que la instrucción llegue a destino',
    hallazgos: ['HAL-009', 'HAL-014'],
    comun: 'Dos cadenas que dependen de terceros —el testigo y el guardia de tienda— y en ninguna existe confirmación de que la instrucción llegó ni estándar que homogenice la ejecución. En ambas el prestador compensa con trabajo adicional que no está medido.',
    riesgo: 'El resultado depende de personas ajenas a la organización sobre las que no hay verificación. Cuando falla, no se puede establecer en qué eslabón se interrumpió la cadena: la falla no es diagnosticable.',
    accion: 'Implantar confirmación de recepción en cada eslabón que dependa de un tercero, y requerir formalmente el estándar donde la ejecución no es propia.',
  },
];

// Plan consolidado de remediación (§11): trece acciones para quince hallazgos.
window.PLAN = [
  { id: 'A', txt: 'Crear la función de gobernanza de definiciones de indicadores', cubre: 'HAL-001 · 003 · 004', resp: 'Dir. Mejora Continua, con validación de Dir. Legal', prio: 'Alta', plazo: 'Pendiente de asignación' },
  { id: 'B', txt: 'Designar dueño por dato crítico y por entregable; diseñar el proceso de control de vigencia y constituir el equipo dedicado ya diseñado', cubre: 'HAL-002 · 007 · 010', resp: 'Gerencia General · Dir. Legal y Compliance', prio: 'Alta', plazo: 'Pendiente de asignación' },
  { id: 'C', txt: 'Implantar la validación independiente contra el Poder Judicial como control previo a todo reporte de estado procesal', cubre: 'HAL-002', resp: 'Dir. Mejora Continua', prio: 'Crítica', plazo: 'Pendiente de asignación' },
  { id: 'D', txt: 'Establecer el procedimiento de gestión de cambios de origen de datos e implantar el identificador único del evento', cubre: 'HAL-006', resp: 'Dir. Tecnología y Sistemas', prio: 'Alta', plazo: 'Pendiente de asignación' },
  { id: 'E', txt: 'Establecer el control de cumplimiento contractual: inventario de obligaciones, opinión legal sobre la vigencia, parámetro de los niveles de servicio y alerta de vencimientos', cubre: 'HAL-005 · 011', resp: 'Dir. Legal y Compliance · Gerencia General', prio: 'Alta', plazo: 'Pendiente de asignación' },
  { id: 'F', txt: 'Rotar las credenciales verificadas, practicar el inventario de accesos y emitir la política de credenciales', cubre: 'HAL-008', resp: 'Dir. Tecnología y Sistemas · Dir. Legal y Compliance', prio: 'Alta', plazo: 'Rotación inmediata; el resto pendiente' },
  { id: 'G', txt: 'Establecer un procedimiento de tratamiento de las observaciones del cliente sobre la información entregada', cubre: 'HAL-002', resp: 'Dir. Customer Success · Dir. Legal y Compliance', prio: 'Crítica', plazo: 'Pendiente de asignación' },
  { id: 'H', txt: 'Implantar confirmación de recepción en la cadena del testigo y dar identidad al testigo en el registro', cubre: 'HAL-009', resp: 'Dir. Customer Success · Subg. Persecución Penal Especializada', prio: 'Alta', plazo: 'Pendiente de asignación' },
  { id: 'I', txt: 'Emitir el protocolo de criminalidad interna, hacer trazable la categoría y ejecutar las dos actuaciones procesales pendientes', cubre: 'HAL-013', resp: 'Subg. Persecución Penal Especializada', prio: 'Crítica', plazo: 'Inmediatas las dos actuaciones procesales' },
  { id: 'J', txt: 'Acordar con el cliente la regla aplicable a la cartera judicializada antes del cambio de modelo', cubre: 'HAL-012', resp: 'Dir. Legal y Compliance', prio: 'Alta', plazo: 'Pendiente de asignación' },
  { id: 'K', txt: 'Requerir formalmente el estándar de los procesos de seguridad en tienda y documentar el retrabajo', cubre: 'HAL-014', resp: 'Dir. Customer Success · frente CCTV y Seguridad', prio: 'Media', plazo: 'Pendiente de asignación' },
  { id: 'L', txt: 'Asignar dueño a la capa de control, seleccionar los elementos que se instrumentan y completar la matriz con los cuatro elementos por proceso', cubre: 'HAL-015', resp: 'Dir. Auditoría Interna (coord.) · áreas responsables', prio: 'Crítica', plazo: 'Pendiente de asignación' },
  { id: 'M', txt: 'Rediseñar el modelo de atención: contraparte única con el nivel de experiencia acordado y destinatario fijo por entregable', cubre: 'HAL-005', resp: 'Gerencia General · Dir. Customer Success', prio: 'Alta', plazo: 'Pendiente de asignación' },
];
